name: sdm-cli
version: '0.0.1'
summary: Command Line Interface to use Sidemash Cloud 
description: |
  sdm is a command line program for creating,
  updating, deleting stream, stream-square:
  - Simple tasks should be easy.
  - Performance trade offs should be exposed
    in the CLI interface.
  - Composition should not come at the
    expense of performance.

confinement: classic
base: core18

parts:
  sdm-cli:
    plugin: rust
    source: https://github.com/sidemash/cli.git

apps:
  sdm-cli:
    command: bin/sidemash-cli
